server:
  port: 8080
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always    
spring:
  boot:
    admin:
      client:
        url: http://localhost:8889
  mvc:
    format:
      date: dd/MM/yyyy
  datasource:
    url: jdbc:postgresql://localhost/hibernate
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        connection:
          driver_class: org.postgresql.Driver
    show-sql: true
    generate-ddl: false
  data:
    jdbc:
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: true  
springdoc:
  api-docs:
    path: /bets-openapi
