server:
  port: 8080
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 789814122841-5su38evfdlpp368585eicmkbpn11p9ss.apps.googleusercontent.com
            client-secret: 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
            #redirect-uri: http://localhost:4200/bets
  boot:
    admin:
      client:
        url: http://localhost:8889
  application:
    name: microservice-one
  mvc:
    format:
      date: dd/MM/yyyy
  datasource:
    url: jdbc:postgresql://postgres/hibernate
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        connection:
          driver_class: org.postgresql.Driver
    show-sql: true
    generate-ddl: false
  data:
    jdbc:
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: true
springdoc:
  api-docs:
    path: /bets-openapi
